[project]
name = "openevolve-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "gymnasium[box2d]>=1.1.1",
    "matplotlib>=3.9.4",
    "optuna>=4.5.0",
    "swig>=4.3.1",
]
